language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=https://github.com/django/django/tarball/master
  - DJANGO=Django==1.6.5
  - DJANGO=Django==1.5.8

install:
  - pip install flake8
  - pip install coverage coveralls
  - pip install -e .
  - pip install $DJANGO

script:
  - flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark teams
  - coverage run setup.py test
  - coverage report

matrix:
  exclude:
   - python: 2.6
     env: DJANGO=https://github.com/django/django/tarball/master
  include:
   - python: 2.7
     env: DJANGO=Django==1.5.8

after_success: coveralls
